import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Check, ChevronDown, Menu, X, Plus, MoveUpRight } from "lucide-react";

const serviceCards = [
  ["Secure Guard", "We fortify your AI deployments with robust security protocols. Our team ensures every model adheres to strict data privacy standards.", "01"],
  ["Agent Build", "Tailored AI agents designed for your specific needs. We develop custom logic and workflows that integrate deeply with your existing tools.", "02"],
  ["Cloud Scale", "Infrastructure optimization for high-traffic AI apps. We ensure your systems remain fast, responsive, and ready for any level of demand.", "03"],
  ["Data Mining", "Transform raw information into actionable intelligence. We build the pipelines and vector stores that power your organization’s future.", "04"],
];
const faqs = [
  ["What is the SOPRANOVA platform?", "SOPRANOVA is a specialized infrastructure for building and deploying custom AI agents. We provide the neural logic and edge nodes required to run autonomous workflows at enterprise scale."],
  ["Who is this template designed for?", "SOPRANOVA is built for ambitious AI agencies, automation studios, and product teams who need a systems-first way to communicate complex capability."],
  ["Does SOPRANOVA provide pre-built agents?", "We provide the foundations, integrations, and patterns to create custom agents that fit the way your organization works."],
  ["How does it differ from a standard chatbot?", "SOPRANOVA orchestrates tools, data, decision trees, and recovery logic — beyond a single conversational interface."],
  ["Can I use my own custom domain?", "Yes. The production-ready system is designed to deploy to your domain and scale with your team."],
  ["Is there a limit to how many agents I can build?", "No artificial cap. Build and manage as many workflows as your infrastructure and team require."],
];

function Pill({ children }: { children: React.ReactNode }) { return <span className="pill">{children}</span> }
function SectionHead({ eyebrow, title, copy, dark=false }: { eyebrow:string; title:string; copy?:string; dark?:boolean }) { return <div className={`section-head ${dark?'light':''}`}><Pill>{eyebrow}</Pill><h2>{title}</h2>{copy && <p>{copy}</p>}</div> }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [faq, setFaq] = useState(0);
  const [email, setEmail] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  useEffect(() => {
    document.body.classList.add("motion-enabled");
    const items = document.querySelectorAll("main section, .service-card, .case-row, .feature-row, .quote-grid blockquote, .article-grid > *, .approach-grid > div");
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); }
    }), { threshold: 0.12 });
    items.forEach((item) => observer.observe(item));
    return () => { observer.disconnect(); document.body.classList.remove("motion-enabled"); };
  }, []);
  const nav = ["Home", "Pricing", "About", "Projects", "Articles", "Contact Us"];
  const go = (id:string) => { document.getElementById(id)?.scrollIntoView({ behavior:"smooth" }); setMenuOpen(false); };
  return <div className="site-shell">
    <header className="topbar"><button className="brand" onClick={()=>go("top")} aria-label="SOPRANOVA home"><img className="brand-mark" src="/manus-storage/sopranova-mark-transparent_2dda676c.png" alt=""/><span>SOPRANOVA</span></button><nav className="top-links"><button onClick={()=>go("about")}>AI Strategy</button><button onClick={()=>go("about")}>Custom Agents</button><button onClick={()=>go("about")}>Process Automation</button><button onClick={()=>go("about")}>Data Intelligence</button></nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen?<X/>:<Menu/>}</button></header>
    {menuOpen && <div className="menu-panel">{nav.map(n=><button key={n} onClick={()=>go(n.toLowerCase().replaceAll(" ","-"))}>{n}<ArrowUpRight size={18}/></button>)}</div>}

    <main id="top">
      <section className="hero section-grid"><div className="hero-visual"><div className="orb orb-a"/><div className="orb orb-b"/><div className="scanline"/><span className="hero-label">// AUTONOMOUS INTELLIGENCE SYSTEMS</span><div className="hero-code">[ 0x7A / ACTIVE ]<br/><span>neural mesh online</span></div></div><div className="hero-copy"><Pill>AI Strategy · Custom Agents · Process Automation · Data Intelligence</Pill><h1>Power your<br/><em>future</em> with AI</h1><p>Deploy custom enterprise agents and automate complex workflows. Scale your intelligence with SOPRANOVA today.</p><button className="primary" onClick={()=>go("contact")}>Build a workflow <ArrowUpRight size={17}/></button></div><div className="hero-footer"><span>Scroll to explore</span><ArrowDownRight/><span>29° 19′ MANCHACA RD<br/>AUSTIN, TX 78704</span></div></section>

      <section className="intro section-grid"><div className="vertical-note">01 / CONNECT</div><div className="intro-copy"><h2>Integrate with the world’s most powerful <span>neural engines.</span></h2><p>Seamlessly connect your custom data to GPT-4, Claude 3, and Perplexity for unmatched precision. Build agents that don’t just process, they understand.</p><p className="muted">Unlock the full potential of LLM-native workflows. Our infrastructure ensures low latency and high-fidelity output for every request.</p></div><div className="model-stack"><div className="model-card active"><span>01</span><strong>GPT-4o</strong><small>OPENAI / ACTIVE</small></div><div className="model-card"><span>02</span><strong>Claude 3.5</strong><small>ANTHROPIC / READY</small></div><div className="model-card"><span>03</span><strong>Perplexity</strong><small>SEARCH / READY</small></div></div></section>

      <section className="services" id="about"><div className="container"><SectionHead eyebrow="02 / CAPABILITIES" title="Built for complex problems." copy="Four layers of intelligence, built to work together."/><div className="service-grid">{serviceCards.map(([title,copy,num])=><article className="service-card" key={title}><span className="card-number">{num}</span><div className="service-icon">↗</div><h3>{title}</h3><p>{copy}</p><a href="#contact">Learn more <ArrowUpRight size={15}/></a></article>)}</div></div></section>

      <section className="stats-band"><div className="container stat-layout"><div><SectionHead dark eyebrow="03 / STATISTICS" title="Quantifiable impact." copy="We measure success by the speed and scale of your neural ops."/><button className="outline light-button" onClick={()=>go("projects")}>View report <ArrowUpRight size={16}/></button></div><div className="big-stats"><div><strong>0<span>ms</span></strong><small>Average latency for real-time inference.</small></div><div><strong>10<span>x</span></strong><small>Increase in manual task processing speed.</small></div><div><strong>99<span>%</span></strong><small>Uptime for critical agent infrastructure.</small></div></div></div></section>

      <section className="case-studies" id="projects"><div className="container"><SectionHead eyebrow="04 / CASE STUDIES" title="Proven neural solutions" copy="We partner with industry leaders to deploy bespoke AI agents that solve complex operational hurdles and drive measurable growth."/><div className="case-list">{[["Cigna Smart Health Systems","Revolutionizing patient care through predictive analytics and seamless AI-driven diagnostic integration tools.","cigna-smart-health","https://framerusercontent.com/images/m5JtYB4nxKXIl9LfLgJMwT1doAY.jpg?width=2731&height=4096"],["Aetna Health Data Ecosystem","We automated Aetna’s member data management using secure AI to provide personalized care and clinical insights.","aetna-health-data","https://framerusercontent.com/images/EuYy1gxty3AwWpl483SuuAIylY.jpg?width=3200&height=2400"],["Anthem Neural Care Network","We deployed a custom LLM to automate Anthem’s provider relations, reducing ticket latency by eighty-five percent.","anthem-neural-care","https://framerusercontent.com/images/2gYwQgOmBPtREHpUtFPcitrFhI.jpg?width=3200&height=2400"]].map(([title,copy,slug,image],i)=><a className="case-row" href={`/details/${slug}`} key={title}><span>//2026</span><div><h3>{title}</h3><p>{copy}</p></div><div className="case-thumb" style={{backgroundImage:`url(${image})`}}/><ArrowUpRight/></a>)}</div><button className="outline" onClick={()=>go("contact")}>More projects <ArrowUpRight size={16}/></button></div></section>

      <section className="product section-grid"><div className="product-copy"><SectionHead eyebrow="05 / OUR PRODUCT" title="Build logic at scale" copy="Design, deploy, and manage sophisticated AI workflows through an intuitive visual interface. No complex coding—just pure logic."/><button className="primary" onClick={()=>go("contact")}>Request demo <ArrowUpRight size={16}/></button></div><div className="workflow-window"><div className="window-top"><span>SOPRANOVA / AGENT MODE</span><span>● LIVE</span></div><div className="workflow-canvas"><div className="node node-a">Email Trigger<small>IMAP</small></div><div className="connector c1"/><div className="node node-b">AI Agent<small>TOOLS AGENT</small></div><div className="connector c2"/><div className="node node-c">Send Email<small>MANUAL</small></div><div className="workflow-label">UNTITLED / 001</div></div></div></section>

      <section className="features"><div className="container feature-layout"><div className="feature-intro"><SectionHead eyebrow="06 / THE SYSTEM" title="The infrastructure behind autonomy."/><div className="terminal">$ SOPRANOVA deploy --production<br/><span>✓ mapping knowledge graph</span><br/><span>✓ connecting 24 integrations</span><br/><span>✓ optimizing neural weights</span><br/><b>_ ready for your next move</b></div></div><div className="feature-list">{[["Infinite Visual Canvas","Map out multi-step agent behaviors on a high-precision grid. Drag and drop triggers, logic gates, and actions to craft custom paths."],["Autonomous Execution","Run complex decision trees without manual intervention. Our engine handles conditional branching and error recovery automatically."],["End-to-End Encryption","Every node and data transfer is shielded by industrial-grade security. Maintain total control over your organizational data flow."],["Production-Ready Stack","Connect core business platforms and internal services through secure, ready integrations that scale with your volume."]].map(([t,c],i)=><div className="feature-row" key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div><Plus size={18}/></div>)}</div></div></section>

      <section className="approach"><div className="container"><SectionHead eyebrow="07 / OUR APPROACH" title="Built for the long term" copy="We don't just ship code; we architect neural ecosystems. Our approach combines rigorous testing with rapid deployment cycles."/><div className="approach-grid">{[["Prime Logic","We prioritize high-fidelity model alignment to ensure your agents deliver consistent results."],["Total Clarity","Gain full observability into how your data is processed, indexed, and retrieved by your AI."],["Fast Cycles","Transition from prototype to production in weeks, not months, with our pre-built frameworks."]].map(([t,c],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></div>)}</div></div></section>

      <section className="feature-dark"><div className="container"><SectionHead dark eyebrow="08 / PRODUCT FEATURES" title="Engineered for autonomy" copy="Go beyond simple chat interfaces. SOPRANOVA provides the underlying architecture to build, test, and scale enterprise-grade agents."/><div className="feature-tabs"><span className="active">DISCOVERY</span><span>ANALYSIS</span><span>TRAINING</span><span>DEPLOY</span></div><div className="feature-art"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="data-label">KNOWLEDGE MAP<br/><b>1,402,928</b> NODES</div><div className="data-label right">INTEGRATIONS<br/><b>24</b> ACTIVE</div></div><p className="feature-caption">Identify latent patterns in unstructured data. Our discovery engine crawls through your silos to map internal knowledge graphs.</p></div></section>

      <section className="testimonials"><div className="container"><SectionHead eyebrow="09 / TESTIMONIALS" title="Trusted by the pioneers" copy="From high-growth startups to enterprise research labs, SOPRANOVA is the chosen infrastructure for teams building the next era of AI."/><div className="quote-grid">{[["Vertex Labs","Infrastructure that finally scales","The reliability of SOPRANOVA is unmatched. We’ve migrated our entire neural pipeline to their edge nodes with zero downtime for our users."],["FlowState AI","Saved us months of R&D","Instead of building our own agent logic from scratch, we used SOPRANOVA. We went from a prototype to a global production launch in weeks."],["Neural Sync","Precision in every inference","The observability tools allow us to monitor agent accuracy in real-time. It has become a vital part of our model evaluation workflow."],["Sentinel Ops","Enterprise-grade by default","The node-based builder is a game changer for our team. Even our non-technical stakeholders can now help map out complex agent behaviors."]].map(([co,t,q])=><blockquote key={co}><span className="quote-mark">“</span><small>{co}</small><h3>{t}</h3><p>{q}</p><footer>★★★★★</footer></blockquote>)}</div></div></section>

      <section className="articles" id="articles"><div className="container"><SectionHead eyebrow="10 / ARTICLES" title="Insights on neural logic" copy="Deep dives into AI architecture, agent automation, and the future of enterprise intelligence. Stay ahead of the neural curve."/><div className="article-grid"><article className="article-feature"><span>APR 29, 2026 · 2 MINS READ</span><h3>What It Takes to Turn AI Into a Business Asset</h3><p>Using AI tools is easy. Turning them into something that drives real outcomes across your business requires structure.</p><a href="#top">Read article <ArrowUpRight size={15}/></a></article><div className="article-list"><a href="#top"><span>APR 29, 2026 · 3 MINS READ</span><h3>Why Your AI Outputs Feel Inconsistent</h3><ArrowUpRight/></a><a href="#top"><span>APR 29, 2026 · 2 MINS READ</span><h3>From Prompting to Systems: The Real Shift in AI</h3><ArrowUpRight/></a></div></div><button className="outline">View articles <ArrowUpRight size={16}/></button></div></section>

      <section className="faq" id="contact"><div className="container faq-layout"><div><SectionHead eyebrow="11 / FAQ" title="Common inquiries" copy="Everything you need to know about deploying, scaling, and securing your neural agents with SOPRANOVA."/><button className="primary" onClick={()=>window.location.href='mailto:hello@sopranova.ai'}>Contact us <ArrowUpRight size={16}/></button></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={`faq-item ${faq===i?'open':''}`} key={q}><button onClick={()=>setFaq(faq===i?-1:i)}><span>{q}</span><ChevronDown size={18}/></button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>

      <section className="newsletter"><div className="container newsletter-inner"><div><Pill>12 / GET STARTED</Pill><h2>Get smarter about<br/><em>AI systems.</em></h2><p>Weekly insights on automation, AI workflows, and real builds. No fluff, just what works.</p></div><form onSubmit={(e)=>{e.preventDefault();setSubscribed(true)}}><label htmlFor="email">YOUR EMAIL</label><div className="email-row"><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/><button className="primary" type="submit">{subscribed?<Check size={17}/>:"Subscribe"}</button></div>{subscribed&&<small className="success">You’re on the list.</small>}</form></div></section>
    </main>
    <footer className="footer"><div className="footer-top"><div><div className="footer-brand">✦ SOPRANOVA</div><p>Seamlessly connect your custom data to GPT-4, Claude 3, and Perplexity.</p><span>2919 MANCHACA RD #102<br/>AUSTIN, TX 78704</span></div><div className="footer-links"><div><b>QUICK LINKS</b>{nav.slice(0,5).map(n=><a href={`#${n.toLowerCase().replaceAll(' ','-')}`} key={n}>{n}</a>)}</div><div><b>COMPANY</b><a href="#about">About Us</a><a href="#contact">Contact Us</a><a href="#contact">Book A Call</a><a href="#top">More Templates</a></div><div><b>POLICIES</b><a href="#top">Terms & Conditions</a><a href="#top">Privacy Policy</a></div></div></div><div className="footer-bottom"><span>SOPRANOVA</span><span>©2026 SOPRANOVA AI. All rights reserved.</span><a href="#top">Back to top <MoveUpRight size={14}/></a></div></footer>
  </div>
}
