import { ArrowUpRight, Check, Mail, MapPin, Phone } from "lucide-react";

const projects = [
  { name: "Cigna Smart Health Systems", type: "Healthcare intelligence", result: "-42% diagnostic workflow time", copy: "A predictive care layer connecting clinical data, care teams, and patient-facing workflows into one secure intelligence system." },
  { name: "Aetna Health Data Ecosystem", type: "Data orchestration", result: "+31% member engagement", copy: "A secure data intelligence program that turns fragmented member signals into timely, personalized care decisions." },
  { name: "Anthem Neural Care Network", type: "Custom agent network", result: "-85% ticket latency", copy: "A provider-relations agent network that handles routing, research, and resolution across a high-volume support operation." },
];

const articles = [
  ["AI systems", "What it takes to turn AI into a business asset", "A practical framework for moving from isolated experiments to measurable operational leverage."],
  ["Agent architecture", "Why your AI outputs feel inconsistent", "The missing layers between a prompt, a model, and a dependable production system."],
  ["Automation", "From prompting to systems: the real shift in AI", "How teams build durable workflows that improve with every interaction."],
];

function PageHeader({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) {
  return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section>;
}

export function Services() {
  return <div className="inner-page"><PageHeader eyebrow="01 / SERVICES" title="Intelligence built for the work that matters." copy="SOPRANOVA helps ambitious teams design, deploy, and operate AI systems that create measurable advantage." /><section className="page-section"><div className="container service-detail-grid">{[["AI Strategy", "Find the highest-value opportunities for AI across your organization. We map the operating model, data reality, and path to production."], ["Custom Agents", "Build agents with memory, tools, permissions, and recovery logic designed around the way your team actually works."], ["Process Automation", "Replace repetitive handoffs with observable workflows that route work, make decisions, and keep people in control."], ["Data Intelligence", "Turn disconnected business data into a reliable intelligence layer for decisions, discovery, and action."]].map(([title,copy],i)=><article className="detail-card" key={title}><span>0{i+1}</span><h2>{title}</h2><p>{copy}</p><a href="/contact">Start a conversation <ArrowUpRight size={16}/></a></article>)}</div></section><section className="dark-callout"><div className="container split-callout"><div><span className="eyebrow">THE SOPRANOVA METHOD</span><h2>Less theatre.<br/>More operating leverage.</h2></div><p>We combine strategy, systems design, and delivery into one focused engagement. The result is not a demo—it is a capability your team can run.</p></div></section></div>;
}

export function Projects() {
  return <div className="inner-page"><PageHeader eyebrow="02 / WORK" title="Systems that move the numbers." copy="Selected engagements where intelligence became a practical operating advantage." /><section className="page-section"><div className="container project-detail-list">{projects.map((p,i)=><article className="project-detail" key={p.name}><div className="project-index">0{i+1}</div><div><span className="eyebrow">{p.type}</span><h2>{p.name}</h2><p>{p.copy}</p><a href="/contact">Read the case study <ArrowUpRight size={16}/></a></div><strong>{p.result}</strong></article>)}</div></section><section className="lime-callout"><div className="container"><span className="eyebrow">YOUR NEXT SYSTEM</span><h2>Have a complex workflow<br/>worth solving?</h2><a className="dark-cta" href="/contact">Talk to SOPRANOVA <ArrowUpRight size={17}/></a></div></section></div>;
}

export function Articles() {
  return <div className="inner-page"><PageHeader eyebrow="03 / INSIGHTS" title="A clearer view of intelligent systems." copy="Field notes on agents, automation, data, and building AI that survives contact with the real world." /><section className="page-section"><div className="container article-detail-grid">{articles.map(([tag,title,copy],i)=><article className="article-detail" key={title}><span className="eyebrow">{tag} · 0{i+1}</span><h2>{title}</h2><p>{copy}</p><a href="/contact">Read insight <ArrowUpRight size={16}/></a></article>)}</div></section></div>;
}

export function Pricing() {
  return <div className="inner-page"><PageHeader eyebrow="04 / PARTNERSHIPS" title="A model that fits the ambition." copy="Start with clarity, then scale the system as the value compounds." /><section className="page-section"><div className="container pricing-grid"><article className="price-card"><span className="eyebrow">FOUNDATION</span><h2>Strategy Sprint</h2><p>For teams that need a focused path from opportunity to an executable AI roadmap.</p><strong>2–4 weeks</strong><ul><li><Check size={16}/> Opportunity and data audit</li><li><Check size={16}/> Prioritized use-case map</li><li><Check size={16}/> Production blueprint</li></ul><a href="/contact">Plan the sprint <ArrowUpRight size={16}/></a></article><article className="price-card featured"><span className="eyebrow">MOST REQUESTED</span><h2>System Build</h2><p>For organizations ready to ship a custom agent or automation capability into production.</p><strong>6–12 weeks</strong><ul><li><Check size={16}/> System architecture</li><li><Check size={16}/> Agent and workflow build</li><li><Check size={16}/> Launch, training, and handoff</li></ul><a href="/contact">Build the system <ArrowUpRight size={16}/></a></article><article className="price-card"><span className="eyebrow">CONTINUOUS</span><h2>Operating Partner</h2><p>For teams that want ongoing optimization, governance, and new capability delivery.</p><strong>Quarterly</strong><ul><li><Check size={16}/> Performance monitoring</li><li><Check size={16}/> New workflow releases</li><li><Check size={16}/> Strategic advisory</li></ul><a href="/contact">Explore partnership <ArrowUpRight size={16}/></a></article></div></section></div>;
}

export function About() {
  return <div className="inner-page"><PageHeader eyebrow="05 / ABOUT" title="We build the intelligence layer behind better work." copy="SOPRANOVA is an AI systems studio for organizations that need more than a chatbot and less than another disconnected tool." /><section className="page-section"><div className="container about-grid"><div><span className="eyebrow">OUR BELIEF</span><h2>AI should make the organization sharper, not noisier.</h2></div><div><p>We bring together product thinking, automation engineering, and data discipline to create systems that are useful on day one and more valuable over time.</p><p>Our work is deliberately practical: clear outcomes, secure foundations, and interfaces that help people make better decisions.</p></div></div></section><section className="dark-callout"><div className="container values-grid">{[["01", "Clarity", "Make the complex legible."], ["02", "Ownership", "Leave teams with a system they can run."], ["03", "Momentum", "Ship the next useful thing quickly."]].map(([n,t,c])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></div>)}</div></section></div>;
}

export function Contact() {
  return <div className="inner-page"><PageHeader eyebrow="06 / CONTACT" title="Bring us the hard problem." copy="Tell us what you are trying to change. We will come back with a sharper set of questions and a practical next step." /><section className="page-section"><div className="container contact-grid"><form className="contact-form" onSubmit={(e)=>e.preventDefault()}><label>Name<input required placeholder="Your name" /></label><label>Work email<input required type="email" placeholder="you@company.com" /></label><label>What are you building?<textarea required rows={5} placeholder="Tell us about the workflow, system, or opportunity." /></label><button className="primary" type="submit">Send inquiry <ArrowUpRight size={17}/></button></form><div className="contact-aside"><div><Mail size={20}/><span>hello@sopranova.ai</span></div><div><Phone size={20}/><span>+1 512 555 0192</span></div><div><MapPin size={20}/><span>Austin · New York · Remote</span></div></div></div></section></div>;
}

export function NotFoundPage() { return <div className="inner-page"><PageHeader eyebrow="404 / NOT FOUND" title="This path does not exist." copy="Return to the SOPRANOVA homepage and continue exploring." /><div className="container not-found-link"><a className="primary" href="/">Back home <ArrowUpRight size={17}/></a></div></div>; }
